[tasks.pyshell]

[tasks.post-build]
script = '''
source .env/bin/activate
maturin develop
'''

[tasks.ipython]
script = '''
source .env/bin/activate
ipython
'''

[tasks.python]
script = '''
source .env/bin/activate
python "${@}"
'''
