redis:
  host: 127.0.0.1
  port: 26379
  database: 0

postgres:
  host: 127.0.0.1
  port: 25432
  user: oomplay
  password: oomplay
  database: oomplay

mysql:
  host: 127.0.0.1
  port: 23306
  user: oomplay
  password: oomplay
  database: oomplay

tidb:
  host: 127.0.0.1
  port: 24000
  user: oomplay
  password: oomplay
  database: oomplay

tikv:
  pd-addrs:
    - 127.0.0.1:22379

cassandra:
  hosts:
    - 127.0.0.1:29042
  user: oomplay
  password: oomplay
  keyspace: oomplay

dynamodb:
  region: .
  endpoint-url: http://127.0.0.1:24566
  access-key-id: .
  secret-access-key: .
  session-token: .
  source: .

sqlite:
  db-file: /tmp/oomplay.db
