[package]
name = "oomstore"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.9"
tokio = { version = "1.15.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.6"

[build-dependencies]
tonic-build = "0.6"
