name: ci
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Build
      run: make build

  lint:
    runs-on: ubuntu-latest
    env:
      golangci-lint-version: 'v1.42.1'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Cache golangci-lint
      uses: actions/cache@v2
      env:
        cache-name: cache-golangci-lint
      with:
        path: ~/bin/golangci-lint
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.golangci-lint-version }}
    - name: Install golangci-lint
      run: |
        echo ~/bin >> $GITHUB_PATH
        ~/bin/golangci-lint --version && exit 0
        mkdir -p ~/bin
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | \
        sh -s -- -b ~/bin ${{ env.golangci-lint-version }}
    - uses: actions/setup-python@v2
    - name: Run pre-commit
      run: |
        pip install pre-commit &&
        pre-commit run --all --show-diff-on-failure

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Install grpcurl
      run: go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
    - name: Install oomplay
      run: |
        wget https://github.com/oom-ai/oomplay/releases/download/v0.1.0/oomplay-musl_0.1.0_amd64.deb &&
        sudo dpkg -i oomplay-musl_0.1.0_amd64.deb
    - name: Run unit tests
      run: make test
      env:
        SNOWFLAKE_TEST_ACCOUNT: ${{ secrets.SNOWFLAKE_TEST_ACCOUNT }}
        SNOWFLAKE_TEST_USER: ${{ secrets.SNOWFLAKE_TEST_USER }}
        SNOWFLAKE_TEST_PASSWORD: ${{ secrets.SNOWFLAKE_TEST_PASSWORD }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    - name: Run integration tests
      run: make integration-test
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.out
        fail_ci_if_error: false
        verbose: true
