name: release

on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set env
        run: echo "REF_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: force sync pkg.go.dev
        run: curl https://sum.golang.org/lookup/github.com/oom-ai/oomstore@${{ env.REF_TAG }}
      - name: Bump Homebrew formula
        uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: oomstore
          homebrew-tap: oom-ai/homebrew-oom-ai
          download-url: https://github.com/oom-ai/oomstore/releases/download/${{ env.REF_TAG }}/oomstore-${{ env.REF_TAG }}-amd64-darwin.tar.gz
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_COMMITTER_TOKEN }}
